import angular = require('angular');

/* import config files */
import { AppConstants } from './_config/app.constants';
import { AppConfig } from './_config/app.config';
import { AppRun } from './_config/app.run';

/* import main libraries */
import 'angular-ui-router';
import 'angular-cookies';
import 'angular-sanitize';
import 'angular-loading-bar';
import 'angular-animate';
import 'angular-ui-bootstrap';
import 'angular-ui-router-uib-modal';
import 'angular-progress-arc';

/* import our templates file (generated by Gulp) */
import './_config/app.templates';

/* assemble app */
import './services';
import './components';
import pages from './pages';

/* set requirements */
let requires = [
    ...[
        'ui.router',
        'ui.bootstrap',
        'ui.router.modal',
        'angular-loading-bar',
        'ngAnimate',
        'ngCookies',
        'ngSanitize',
        'templates',
        'app.services',
        'app.components',
        'angular-progress-arc'
    ],
    ...pages
];

angular.module('app', requires);

angular.module('app').constant('AppConstants', AppConstants);

angular.module('app').config(AppConfig);

angular.module('app').run(AppRun);

angular.bootstrap(document, ['app'], {
    strictDi: false
});
